### ISSUE TITLE
use

### ISSUE THREAD

**Issue by yangxiongj** [ResearchHelper/research-helper#27]
![image](https://user-images.githubusercontent.com/41324846/234063454-4cf2eb5f-f229-4979-983e-e16abaf9b86f.png)
![image](https://user-images.githubusercontent.com/41324846/234063507-fbb6dff9-2abc-4d8e-b1b9-02d9795d81a6.png)
I can't understand how to use it

**Comment by HuntFeng** [comment]
- If you want to use the app only, download the corresponding executable in the [newest release](https://github.com/ResearchHelper/research-helper/releases/tag/v1.0.0-beta).
- If you want to contribute (or develop your own version of research-helper), you can do the followings

1. Clone the project, and `cd` into the project folder
```
git clone git@github.com:ResearchHelper/research-helper.git
cd research-helper
```
2. Install dependencies (yarn is recommended)
```
yarn
```
3. Start development
```
yarn dev
```
By doing `yarn dev`, `pouchdb-server` will be automatically started on port 3000 for debugging. You can use the built-in pouchdb utils by accessing `http://localhost:3000/_utils/` in your browser.

If you want to develop a cloud storage feature, you will need to use CouchDB for production rather than pouchdb server.

**Comment by yangxiongj** [comment]
Do you have a web version, not an exe

**Comment by HuntFeng** [comment]
Since the app needs to store data in your computer, I'm not so sure web version is a good idea. 

But I get it, you can use something like grammarly if it's a web. I'll consider this feature after plugin system is implemented.
